### PR TITLE
Mainframes and Channel I/O article

### PR DESCRIPTION
**Pull request by sam-falvo**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Yay, mainframes!  Obsolete technology waiting to be reinvented.

**Comment by sam-falvo** [comment]
I'm confused; are you in support or opposition to my new direction with the project?

Regarding relevance, mainframes have never truly been obsolete.  I'd argue instead that they're niche, but not obsolete.  Modern zArchitecture mainframes are gobsmackingly awesome at what they do.

Apologies if I "don't get it."  Thanks.

**Comment by larsbrinkhoff** [comment]
Sorry for the confusion.  I was just curious to see the word "mainframe".  I'm one of those people who refuse to let the PDP-10 rest in piece.

I'm not opposing anything.  Happy hacking!

**Comment by sam-falvo** [comment]
Ahh!!  Thanks for the clarification!  Without the nuance of intonation, it was difficult to interpret "obsolete technology waiting to be reinvented" as affirmation or consternation, as it could easily be taken as either depending on context.  Thanks!

**Comment by sam-falvo** [comment]
Speaking of PDP-10, you should get in touch with a friend of mine, https://github.com/sethm, as he recently received a number of materials related to TOPS-10 (TOPS-20?  I forget which) and is playing around with a machine which apparently is still online somewhere on the Internet.  He really enjoys the platform.

**Comment by larsbrinkhoff** [comment]
Thanks, he has already joined the [PDP-10 organization](http://github.com/PDP-10).  I think everyone who posted to alt.sys.pdp10 in the last ten years has got an invitation.

**Pull request merged**
