### PR TITLE
VIBE 2.2 source release

### PR DESCRIPTION
**Pull request by sam-falvo**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
First update in over ten years?

**Comment by sam-falvo** [comment]
Heh, yep.  :)  Although, it turns out I won't even be using it.  I was thinking I could edit the sources in block storage, so it'd be easier to share source code between Linux and the Kestrel.  But, in retrospect, that's a bad idea (cannot apply source control, for starters).  Not like I invested a lot of work into it though.  Just fixed a few lingering bugs.  :)

**Comment by larsbrinkhoff** [comment]
I'm curious about source blocks.  Regarding source control (or otherwise using Unix tools), how about adding the convention that the last character of every block line must be a newline?

**Comment by sam-falvo** [comment]
That's .... a possibility.  I'll need to play with that!  Thanks for the suggestion.

**Comment by larsbrinkhoff** [comment]
There's also this:
https://github.com/programandala-net/fsb2

**Pull request merged**
